name: chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  EXECUTABLES: "my_paint"
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-PSU-200-MPL-2-1-42sh-elias-josue.hajjar-llauquen.git"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    if: github.repository != 'git@github.com:EliasJHL/42sh.git'
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check_coding
        run: check.sh $(pwd) $(pwd)
      - name: coding
        run: |
          if [ -s coding-style-reports.log ]; then
            while IFS= read -r line
            do
              FILE=$(echo $line | cut -d':' -f1)
              LINE=$(echo $line | cut -d':' -f2)
              MSG=$(echo $line | cut -d':' -f3)
              echo "::error file=$FILE,line=$LINE::$MSG"
            done < coding-style-reports.log
            exit 1
          fi
          rm -f coding-style-reports.log
  
  check_program_compilation:
    runs-on: ubuntu-latest
    needs: [check_coding_style]
    if: ${{ needs.check_coding_style.result == 'success' }}
    container:
      image: epitechcontent/epitest-docker:latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: make_command
        run: make
        timeout-minutes: 2
      - name: clean_command
        run: make clean
      - name: check_exec
        run: |
          for file in $EXECUTABLES; do
            if [ ! -x "$file" ]; then
              echo "Error: $file is either missing or not executable."
            exit 1
          fi
            exit 0
          done

  run_tests:
    needs: [check_program_compilation]
    if: ${{ needs.check_program_compilation.result == 'success' }}
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    needs: [run_tests]
    if: ${{ needs.run_tests.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}